[program:mqtt]
command=/usr/bin/python3 /usr/local/bin/irrigator/mqtt.py
directory=/usr/local/bin/irrigator
autostart=true
startsecs=0
autorestart=unexpected
exitcodes=0
startretries=3
stderr_logfile=/usr/local/bin/irrigator/logs/mqtt.err.log
stdout_logfile=/usr/local/bin/irrigator/logs/mqtt.out.log
user=root
