[program:mqtt]
command=/usr/local/bin/irrigator/.venv/bin/python /usr/local/bin/irrigator/mqtt.py
directory=/usr/local/bin/irrigator
autostart=true
autorestart=true
startretries=3
stderr_logfile=/usr/local/bin/irrigator/logs/mqtt.err.log
stdout_logfile=/usr/local/bin/irrigator/logs/mqtt.out.log
user=root
